export const message = {
   USER_REGISTRATION_FAILUER : "USER REGISTRATION FAILD",
   USER_ALREADY_EXIST : "USER ALREADY  EXIST",
   USER_CREATION_FAILUER : "USER CREATION FAILD",
   USER_CREATION_SUCCESS : "USER CREATION SUCCESSFULL",
   USER_NOT_FOUND : "USER NOT FOUND",
   USER_EMPTY_BODY:"ALL FIELD ARE EMPTY", 
   TOKEN_GENERATION_SUCCESS:"TOKEN GENERATION SUCCESSFULL",
   USER_NOT_AUTHORIZED:"USER NOT AUTHORIZED",
   USER_NOT_AUTHENTICATE : "USER NOT AUTHENTICATE , TOKEN IS REQUIRED TO AUTHENTICATE",
   USER_NOT_FOUND:"USER NOT FOUND",

   INVALID_DATE : "Invalid date format. Use ISO format.",
   USER_EMPTY_BODY: "Please provide all required fields.",
   EVENT_CREATION_SUCCESS: "Event created successfully.",
   EVENT_UPDATE_SUCCESS: "Event updated successfully.",
   EVENT_DELETE_SUCCESS: "Event deleted successfully.",
   EVENT_NOT_FOUND_OR_DELETED: "Event not found or already deleted.",
   EVENT_FETCH_SUCCESS: "Event fetched successfully.",

   RSVP_FETCH_SUCCESS: "RSVP responses fetched successfully",
  EVENT_NOT_FOUND: "Event not found",

   TOKEN_GENERATION_FAILD:"TOKEN GENERATION FAILD",
   INVALID_TOKEN:"INVALID TOKEN",


   PRIORITY_RANGE_FAILUER:"PRIORITY MUST BE BETWEEN 1 AND 5",
   INVALID_STATUS_VALUE : "INVALID STATUS VALUE",


  
}

